# Give the workflow a name.
name: update-csv

# Trigger Workflow every midnight UTC

on:
  push
  schedule:
    - cron: '0 19 * * *'
#workflow_dispatch helps run workflow anytime with a single click.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Scheduling
    # make sure to run this action in Linux env (say ubuntu)
    env:
      API_KEY: ${{ secrets.API_KEY }}
      API_SECRET: ${{ secrets.API_SECRET }}
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
      WP_USER: ${{ secrets.WP_USER }}
      WP_PASSWORD: ${{ secrets.WP_PASSWORD }}

    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pip3 install -r requirements.txt
      - name: Update stuff
        run: python3 upload-csv.py
